### ISSUE TITLE
Replace deprecated request library

### ISSUE THREAD

**Issue by diracdeltas** [brave/web-discovery-project#285]
the request library is no longer getting updates, so the only way to resolve https://github.com/brave/web-discovery-project/security/dependabot/17 is to replace it with an alternative like axios.

**Comment by bcaller** [comment]
request is a dependency of [mozilla/sign-addon](https://github.com/mozilla/sign-addon/)
sign-addon is a dependency of [mozilla/web-ext](https://github.com/mozilla/web-ext)

According to the [issue in sign-addon](https://github.com/mozilla/sign-addon/issues/933):
> Our plan is to fully get rid of sign-addon in web-ext v8 (we are currently at v7). We considered updating this library with node-fetch or got or something else but the cost of maintaining two implementations[1](https://github.com/mozilla/sign-addon/issues/933#user-content-fn-1-993b050ae5507b0c18d2f25e29a0b5fc) is getting too high.

I'll look into what we can do before v8 of web-ext fixes this.

**Comment by bcaller** [comment]
I dismissed this alert.

> The WDP extension does not perform any signing of addon so we are not
reaching [the code-path](https://github.com/mozilla/web-ext/blob/345ebd8ebd34f716bcf6d74cd67a09e827184c8b/src/cmd/sign.js#L5) that is potentially impacted

> We only use web-ext locally while developing to start a browser with the WDP extension loaded.

Also there is no easy fix.
