### ISSUE TITLE
CI should be running npm/yarn audit on PRs

### ISSUE THREAD

**Issue by diracdeltas** [brave/web-discovery-project#82]
We are seeing increasing builds fail in brave-core due to npm audit issues introduced by this repo. To surface these easier, PRs here should fail whenever there is an error in npm audit.

**Comment by diracdeltas** [comment]
Currently npm audit seems to be only running in the `release` workflow

**Comment by remusao** [comment]
Sounds good. Although dependencies can get vulnerable without us having to open PRs on WDP. So we might block the first PR unrelated to dependencies because of the check.
